"""Anexo A del contrato de Onboarding B2B: los 238 países y su nombre en español.

GENERADO desde `anexo-a-paises-country-code-enum.csv` (v1.2, 25-sep-2026). No se
edita a mano: si tech manda un anexo nuevo, se regenera.

Por qué existe esta tabla y no se manda el texto tal cual sale del documento:
Onboarding compara el nombre del país **ignorando mayúsculas y espacios de los
extremos, pero NO la grafía**. `Mexico` sin tilde no coincide con `México` y se
guarda como país desconocido — sin dar error. Así que LENS tiene que emitir
exactamente la grafía de esta tabla.

El emparejamiento de este lado SÍ es tolerante (ver `onboarding.pais_anexo_a`):
se compara sin tildes y sin distinguir mayúsculas, y se emite la forma canónica.
Tolerante al leer, estricto al escribir.
"""

from __future__ import annotations

# (código ISO, nombre esperado en español)
PAISES: tuple[tuple[str, str], ...] = (
    ('AR', 'Argentina'),
    ('BR', 'Brasil'),
    ('CL', 'Chile'),
    ('CO', 'Colombia'),
    ('EC', 'Ecuador'),
    ('MX', 'México'),
    ('PE', 'Perú'),
    ('US', 'Estados Unidos'),
    ('AF', 'Afganistán'),
    ('AX', 'Åland'),
    ('AL', 'Albania'),
    ('DZ', 'Argelia'),
    ('AS', 'Samoa Americana'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AI', 'Anguila'),
    ('AG', 'Antigua y Barbuda'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AZ', 'Azerbaiyán'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrein'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Bielorrusia'),
    ('BE', 'Bélgica'),
    ('BZ', 'Belice'),
    ('BJ', 'Benin'),
    ('BM', 'Bermudas'),
    ('BT', 'Bután'),
    ('BO', 'Bolivia'),
    ('BQ', 'Bonaire'),
    ('BA', 'Bosnia y Herzegovina'),
    ('BW', 'Botswana'),
    ('IO', 'Territorio Británico del Océano Índico'),
    ('VG', 'Islas Vírgenes Británicas'),
    ('VI', 'Islas Vírgenes de los Estados Unidos'),
    ('BN', 'Brunei Darussalam'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('KH', 'Camboya'),
    ('CM', 'Camerún'),
    ('CA', 'Canadá'),
    ('CV', 'Cabo Verde'),
    ('KY', 'Islas Caimán'),
    ('CF', 'República Centroafricana'),
    ('TD', 'Chad'),
    ('CN', 'China'),
    ('CX', 'Isla de Navidad'),
    ('CC', 'Islas Cocos'),
    ('KM', 'Comoras'),
    ('CG', 'Congo'),
    ('CD', 'República Democrática del Congo'),
    ('CK', 'Islas Cook'),
    ('CR', 'Costa Rica'),
    ('HR', 'Croacia'),
    ('CU', 'Cuba'),
    ('CW', 'Curazao'),
    ('CY', 'Chipre'),
    ('CZ', 'República Checa'),
    ('DK', 'Dinamarca'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'República Dominicana'),
    ('EG', 'Egipto'),
    ('SV', 'El Salvador'),
    ('GQ', 'Guinea Ecuatorial'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('ET', 'Etiopía'),
    ('FK', 'Islas Malvinas'),
    ('FO', 'Islas Faroe'),
    ('FJ', 'Fiji'),
    ('FI', 'Finlandia'),
    ('FR', 'Francia'),
    ('GF', 'Guiana Francesa'),
    ('PF', 'Polinesia Francesa'),
    ('GA', 'Gabón'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Alemania'),
    ('GH', 'Ghana'),
    ('GI', 'Gibraltar'),
    ('GR', 'Grecia'),
    ('GL', 'Groenlandia'),
    ('GD', 'Granada'),
    ('GP', 'Guadalupe'),
    ('GU', 'Guam'),
    ('GT', 'Guatemala'),
    ('GG', 'Guernsey'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haití'),
    ('VA', 'Ciudad del Vaticano'),
    ('HN', 'Honduras'),
    ('HK', 'Hong Kong'),
    ('HU', 'Hungría'),
    ('IS', 'Islandia'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('CI', 'Costa de Marfil'),
    ('IR', 'Irán'),
    ('IQ', 'Irak'),
    ('IE', 'Irlanda'),
    ('IM', 'Isla de Man'),
    ('IL', 'Israel'),
    ('IT', 'Italia'),
    ('JM', 'Jamaica'),
    ('JP', 'Japón'),
    ('JE', 'Jersey'),
    ('JO', 'Jordania'),
    ('KZ', 'Kazajstán'),
    ('KE', 'Kenia'),
    ('KI', 'Kiribati'),
    ('KW', 'Kuwait'),
    ('KG', 'Kirguistán'),
    ('LA', 'Laos'),
    ('LV', 'Letonia'),
    ('LB', 'Líbano'),
    ('LS', 'Lesoto'),
    ('LR', 'Liberia'),
    ('LY', 'Libia'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lituania'),
    ('LU', 'Luxemburgo'),
    ('MO', 'Macao'),
    ('MK', 'Macedonia del Norte'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malasia'),
    ('MV', 'Maldivas'),
    ('ML', 'Malí'),
    ('MT', 'Malta'),
    ('MH', 'Islas Marshall'),
    ('MQ', 'Martinica'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauricio'),
    ('YT', 'Mayotte'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldavia'),
    ('MC', 'Mónaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MS', 'Montserrat'),
    ('MA', 'Marruecos'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Países Bajos'),
    ('NC', 'Nueva Caledonia'),
    ('NZ', 'Nueva Zelanda'),
    ('NI', 'Nicaragua'),
    ('NE', 'Níger'),
    ('NG', 'Nigeria'),
    ('NU', 'Niue'),
    ('NF', 'Isla Norfolk'),
    ('KP', 'Corea del Norte'),
    ('MP', 'Islas Marianas del Norte'),
    ('NO', 'Noruega'),
    ('OM', 'Omán'),
    ('PK', 'Pakistán'),
    ('PW', 'Palau'),
    ('PS', 'Palestina'),
    ('PA', 'Panamá'),
    ('PG', 'Papau Nueva Guinea'),
    ('PY', 'Paraguay'),
    ('PH', 'Filipinas'),
    ('PL', 'Polonia'),
    ('PT', 'Portugal'),
    ('PR', 'Puerto Rico'),
    ('QA', 'Qatar'),
    ('RE', 'Reunión'),
    ('RO', 'Rumania'),
    ('RU', 'Rusia'),
    ('RW', 'Ruanda'),
    ('BL', 'San Bartolomé'),
    ('SH', 'Isla Santa Elena'),
    ('LC', 'Santa Lucía'),
    ('MF', 'Isla de San Martín'),
    ('PM', 'San Pedro y Miquelón'),
    ('VC', 'San Vicente y las Granadinas'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Santo Tomé y Príncipe'),
    ('SA', 'Arabia Saudita'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapur'),
    ('SX', 'San Martín'),
    ('SK', 'Eslovaquia'),
    ('SI', 'Eslovenia'),
    ('SB', 'Islas Salomón'),
    ('SO', 'Somalia'),
    ('ZA', 'Sudáfrica'),
    ('KR', 'Corea del Sur'),
    ('SS', 'Sudán del Sur'),
    ('ES', 'España'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudán'),
    ('SR', 'Surinam'),
    ('SZ', 'Esuatini'),
    ('SE', 'Suecia'),
    ('CH', 'Suiza'),
    ('SY', 'Siria'),
    ('TW', 'Taiwán'),
    ('TJ', 'Tayikistán'),
    ('TZ', 'Tanzania'),
    ('TH', 'Tailandia'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TK', 'Tokelau'),
    ('TO', 'Tonga'),
    ('TT', 'Trinidad y Tobago'),
    ('TN', 'Túnez'),
    ('TR', 'Turquía'),
    ('TM', 'Turkmenistán'),
    ('TC', 'Islas Turcas y Caicos'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ucrania'),
    ('AE', 'Emiratos Árabes Unidos'),
    ('GB', 'Reino Unido'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistán'),
    ('VU', 'Vanuatu'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('WF', 'Wallis y Futuna'),
    ('EH', 'Sahara Occidental'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabue'),
)

NOMBRES: tuple[str, ...] = tuple(n for _, n in PAISES)
POR_ISO: dict[str, str] = {iso: n for iso, n in PAISES}
